config/routes.rb
# Upgrade 2.0.0 inizio
Rails.application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resources :users do
    put 'toggle_active', on: :member
  end

  # Polymorphic resources (must be here, prior to parent resources)
  resources :digital_objects, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end
  resources :group_images, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end

  resources :groups do
    resources :group_carousel_images, :except => [:show, :destroy], :controller => "group_images", :type => "carousel"
    resources :group_logo_images, :except => [:show, :destroy], :controller => "group_images", :type => "logo"
  end

  resources :fonds, :except => [:new] do
    member do
      get    :tree
      get    :treeview
      put    :ajax_update
      patch  :ajax_update
      put    :rename
      put    :move
      get    :merge_with
      post   :merge
      get    :split_fond
      post   :split
      get    :trash
      get    :trashed_subtree
      put    :move_to_trash
      put    :restore_subtree
      delete :destroy_subtree
      put    :publish
      put    :unpublish
    end
    collection do
      get  :save_a_tree
      post :saving_the_tree
      get  :list
      post :ajax_create
    end

    resources :units do
      collection do
        get  :gridview
        post :gridview
        get  :grid
        post :add_rows
        put  :remove_rows
        put  :reorder_rows
# Upgrade 2.1.0 inizio
#        get  :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :units, :except => [:new] do
    member do
      put   :ajax_update
      patch :ajax_update
      get   :render_full_path
      get   :preferred_event
      get   :textfield_form
      put   :update_event
# Upgrade 2.1.0 inizio
#      get   :edit_iccd
#      get   :show_iccd
# Upgrade 2.1.0 fine
      get   :move
      post  :move_down
      post  :move_up
    end
    collection do
      get :list_oa_mtc
      get :list_oa_ogtd
      get :list_bdm_ogtd
      get :list_bdm_mtcm
      get :list_bdm_mtct
# Upgrade 2.1.0 inizio
      get :sc2_voc_list
# Upgrade 2.1.0 fine
      put :classify
    end

    # OPTIMIZE: rinominare in subunits ?
    resources :children, :controller => 'units', :only => 'new' do
      collection do
# Upgrade 2.1.0 inizio
#        get :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :creators do
    collection do 
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :custodians do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :sources do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :institutions do
    collection do
      get :list
    end
  end

  resources :document_forms do
    collection do
      get :list
    end
  end

  resources :projects do
    collection do
      get :list
      put :publish
      put :unpublish
    end
  end

  resources :editors do
    collection do
      get  :list
      get  :modal_new
      post :modal_create
    end
  end

  # Strumenti
  resources :headings do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :anagraphics do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :reports, :only => [:index] do
    member do
      get  :dashboard
      get  :summary
      get  :inventory
      post :inventory
      get  :creators
      get  :custodians
      get  :labels
      get  :units
      get  :custodian
      post :custodian
      get  :project
      post :project
    end
    collection do
      get :download
    end
  end

  resources :quality_checks, :only => [:index] do
    member do
      get :fond
      get :creator
      get :custodian
    end
  end

# Upgrade 3.0.0 inizio
resources :multiple_occours, :only => [:index] do
    member do
      post :merge
    end
  end
# Upgrade 3.0.0 fine

  resources :imports, :only => [:index, :new, :create, :destroy]
  resources :exports, :only => [:index] do
    collection do
      get :download
      get :xml
      get :fonds_aef
      get :units_ead
      # Upgrade 2.2.0 inizio
      post :units
      # Upgrade 2.2.0 fine
    end
  end
  resources :exports_batch, :only => [:index] do
    collection do
      post :icarimport
      post :aefallfonds
      post :aeffondsnoancestry
      post :aefallfondsnoancestry
      post :aefprojects
      post :aefallprojects
      post :aefcustodiansproject
      post :aefcustodians
      post :aefallcustodians
      post :xmlallfonds
      post :xmlfondsnoancestry
      post :xmlallfondsnoancestry
      post :xmlsourcesproject
      post :xmlsources
      post :xmlallsources
    end
  end    

  # Vocabolari
  resources :vocabularies, :only => [:index]

  resources :creator_corporate_types, :only => [:index]
  resources :custodian_types, :only => [:index]
  resources :source_types, :only => [:index]

  resources :activities, :only => [:index] do
    collection do
      get :list
    end
  end
  resources :places, :only => [:index] do
    collection do
      get :cities
      get :countries
    end
  end
  resources :langs, :only => [:index]

  # Non-Resourceful Routes
  root :to => 'site#dashboard'
  resources :about, :only => [:index], :to => "site#about"
  match :parse_textile, :only => [:index], :to => "site#parse_textile", :via => [:get, :post]

end

# Upgrade 2.0.0 fine

app/controllers/quality_checks_controller.rb
class QualityChecksController < ApplicationController
  helper_method :creator_source, :creator_fond

  def index

    if params[:fond_id].present?
      redirect_to :action => 'fond', :id => params[:fond_id], :complete => params[:complete]
    end

    if params[:creator_id].present?
      redirect_to :action => 'creator', :id => params[:creator_id]
    end

    if params[:custodian_id].present?
      redirect_to :action => 'custodian', :id => params[:custodian_id]
    end

    @fonds = Fond.list.
      roots.
      accessible_by(current_ability, :read).
      active.
      default_order

    @creators = Creator.list.accessible_by(current_ability, :read)
    @custodians = Custodian.list.accessible_by(current_ability, :read)

  end

  def fond
# Upgrade 2.0.0 inizio
#    @fonds = Fond.subtree_of(params[:id]).active.all(:include => :preferred_event, :order => "sequence_number")
    @fonds = Fond.subtree_of(params[:id]).active.includes(:preferred_event).order("sequence_number")
# Upgrade 2.0.0 fine

    # campi minimi
    @fonds_with_no_name = @fonds.select { |e| e.name.blank? || e.name == '[nome non compilato]'}
    @fonds_with_no_event = @fonds.select { |e| e.preferred_event.blank? }
    @fonds_with_no_fond_type = @fonds.select { |e| e.fond_type.blank? }

    # campi per un record "decoroso" => solo se inventario?
    @fonds_with_no_description = @fonds.select { |e| e.description.blank? }
    @fonds_with_no_history = @fonds.select { |e| e.history.blank? }
    @fonds_with_no_length = @fonds.select { |e| e.length.blank? }

# Upgrade 3.0.0 inizio
# Potenziamento controllo qualità con l'aggiunta della relazione fondo-progetto
    @fonds_with_no_units = @fonds.select { |e| e.units_count == 0 }
# Upgrade 3.0.0 fine    

    @fond_root_name = @fonds.first.name

    ids = @fonds.map(&:id).join(',')

# Upgrade 2.0.0 inizio
=begin
    @creators  =  Creator.all(
      :joins => :rel_creator_fonds,
      :conditions => "rel_creator_fonds.fond_id IN (#{ids})",
      :include => [:preferred_name, :preferred_event])
=end
    @creators  =  Creator.
      joins(:rel_creator_fonds).
      where("rel_creator_fonds.fond_id IN (#{ids})").
      includes([:preferred_name, :preferred_event])
      .group(:creator_id)
# Upgrade 2.0.0 fine

# Upgrade 2.0.0 inizio
=begin
    @custodians = Custodian.all(
      :joins => :rel_custodian_fonds,
      :conditions => "rel_custodian_fonds.fond_id IN (#{ids})",
      :include => [:preferred_name, :custodian_buildings])
=end
    @custodians = Custodian.
      joins(:rel_custodian_fonds).
      where("rel_custodian_fonds.fond_id IN (#{ids})").
      includes([:preferred_name, :custodian_buildings])
# Upgrade 2.0.0 fine

# Upgrade 3.0.0 inizio
# Potenziamento controllo qualità con l'aggiunta della relazione fondo-progetto, fondo-fonti e produttore-fonti

    @projects = Project.
      joins(:rel_project_fonds)
      .where("rel_project_fonds.fond_id IN (#{params[:id]})")

    @fonds_with_sources = Fond.
      joins(:rel_fond_sources)
      .where("rel_fond_sources.fond_id IN (#{ids})")
      .group(:fond_id)
# Upgrade 3.0.0 fine
  end

  def creator
    @creator = Creator.find(params[:id])
  end

  def custodian
    @custodian = Custodian.find(params[:id])
  end

  def creator_source(id)
     @creator = RelCreatorSource.where("rel_creator_sources.creator_id IN (#{id})")
  end

  def creator_fond(id)
    fond = Fond.find(id)
  end

end

app/views/quality_checks/_creator.html.erb
<h3 class="section">Requisiti minimi</h3>
<table class="table">
  <tr>
    <th style="width:25%;"><%= t('creator_type') %></th>
    <td>
      <% if creator.creator_type.present? %>
        <%= show_value(creator.creator_type, "t") %>
      <% else %>
        <%= warning_field %>
      <%  end %>
    </td>
  </tr>
  <% if creator.is_corporate? %>
    <tr>
      <th><%= t('creator_corporate_type') %></th>
      <td>
        <% if creator.creator_corporate_type.present? %>
          <%= creator.creator_corporate_type.corporate_type.capitalize %>
        <% else %>
          <%= warning_field %>
        <% end %>
      </td>
    </tr>
  <% end -%>
  <tr>
    <th><%= t('preferred_name') %></th>
    <td>
      <% if creator.preferred_name.name.present? %>
        <% if creator.preferred_name.name == '[nome non compilato]' %>
          <span class="red"><%= creator.preferred_name.name %></span>
        <% else %>
          <%= creator.preferred_name.name %>
        <% end %>
      <% else %>
        <%= warning_field %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th><%= t('date_event')%></th>
    <td>
      <% if creator.preferred_event.present? %>
          <%= creator.preferred_event.full_display_date_with_place %>
      <% else %>
        <%= warning_field %>
      <% end %>
    </td>
  </tr>
</table>

<%# Upgrade 3.0.0 inizio %>
  <h4>1. <%= t('creator_history')  %> </h4>
  <% if creator.history.present? %>
    <p><i class="icon-ok-sign"></i> <%= raw(t('count.creator_history.success', :field => t('creator_history'))) %></p>
  <% else %>
    <table class="table">
    <thead>
        <tr>
          <th style="width:90%;">&nbsp;</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td>
              <%= raw(t('count.creator_history.failure', :field => t('creator_history'))) %>
            </td>
            <td>
              <%= link_to 'modifica', edit_source_path(creator) %>
            </td>
          </tr>
      </tbody>
    </table>
<% end %>

<h4>2. <%= t('sources')  %> </h4>
  <%  cr_s = creator_source(creator.id)  %>
  <% f = creator_fond(fond) %>
  <% if cr_s.count.zero? %>
    <p><i class="icon-exclamation-sign"></i> <%= raw(t('count.creator_sources.failure', :count => cr_s.count )) %></p>
  <% else %>
    <table class="table">
    <thead>
        <tr>
          <th style="width:90%;">&nbsp;</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td>
              <%= raw(t('count.creator_sources.success', :count => cr_s.count)) %>
            </td>
            <td>
              <%= link_to 'modifica', treeview_fond_path(f) %>
            </td>
          </tr>
      </tbody>
    </table>
  <%  end %>
<%# Upgrade 3.0.0 fine %>
<hr style="border-width: 2px 0;">

app/views/quality_checks/_custodian.html.erb
<h3 class="section">Requisiti minimi</h3>
<table class="table">
  <tr>
    <th style="width:25%;"><%= t('preferred_name') %></th>
    <td>
      <% if custodian.preferred_name.name.present? %>
        <%= custodian.preferred_name.name %>
      <% else %>
        <%= warning_field %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th><%= t('custodian_macro_type') %></th>
    <td>
      <% if custodian.custodian_type.present? %>
        <%= custodian.custodian_type.custodian_type.capitalize %>
      <% else %>
        <%= warning_field %>
      <% end %>
    </td>
  </tr>
  <% unless custodian.custodian_buildings.size.zero? %>
    <% custodian.custodian_buildings.each do |custodian_building| %>
      <tr>
        <th><%= show_item(custodian_building.custodian_building_type.capitalize, ["", ""]) %></th>
        <td>
          <%= show_item(custodian_building.name, ["", "<br />"]) %>
          <%= show_item(custodian_building.address, ["", "<br />"]) %>
          <%= show_item(custodian_building.postcode) %>   <%= show_item(custodian_building.city, ["", "<br />"]) %>
          <%= show_item(custodian_building.state) %> <%= show_item(custodian_building.country) %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <th><%= t('buildings') %></th>
      <td><%= warning_field %></td>
    </tr>
  <% end %>
</table>

app/views/quality_checks/_fond.html.erb
<table class="table">
  <thead>
    <tr>
      <th>tipologia</th>
      <th>denominazione</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% object.each do |fond| %>
      <tr>
        <td>
          <%= fond.fond_type.present? ? fond.fond_type : warning_field %>
        </td>
        <td>
          <%= fond.name.present? ? fond.name : warning_field %>
        </td>
        <td>
          <%= link_to 'modifica', treeview_fond_path(fond) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/quality_checks/_project.html.erb
<table class="table">
  <tr>
    <th style="width:25%;"><%= t('name') %></th>
    <td>
      <% if project.name.present? %>
        <%= project.name %>
      <% else %>
        <%= warning_field %>
      <% end %>
    </td>
  </tr>


</table>

app/views/quality_checks/creator.html.erb
<% content_for :status_bar do %>
  <h2>Controllo qualità<%= path_separator %><%= t('creators') %></h2>
  <div id="links">
    <%= link_to_index "Controllo qualità", quality_checks_path %>
  </div>
<% end %>
<div class="span12">
<%# Upgrade 2.0.0 inizio %>
  <%#= render :partial => "creator" %>
  <%= render :partial => "creator", :object => @creator, as: "creator" %>
<%# Upgrade 2.0.0 fine %>
</div>

app/views/quality_checks/custodian.html.erb
<% content_for :status_bar do %>
  <h2>Controllo qualità<%= path_separator %><%= t('custodians') %></h2>
  <div id="links">
    <%= link_to_index "Controllo qualità", quality_checks_path %>
  </div>
<% end %>
<div class="span12">
<%# Upgrade 2.0.0 inizio %>
  <%#= render :partial => "custodian" %>
  <%= render :partial => "custodian", :object => @custodian, as: "custodian" %>
<%# Upgrade 2.0.0 fine %>
</div>

app/views/quality_checks/fond.html.erb
<% content_for :status_bar do %>
  <% if params[:complete] %>
    <h2>Controllo qualità<%= path_separator %>descrizione completa</h2>
  <% else %>
    <h2>Controllo qualità<%= path_separator %>complesso archivistico</h2>
  <% end %>
  <div id="links">
    <%=  link_to_index "Controllo qualità", quality_checks_path %>
  </div>
<% end %>

<div class="span12">
  <h2><%= @fond_root_name %></h2>

<%# OPTIMIZE: [very low] dopo assestamento funzionalità e vista, i18n e inflection singolare/plurale %>

  <h3 class="section">Requisiti minimi</h3>

  <h4>1. <%=  t('name') %></h4>

  <% if @fonds_with_no_name.count.zero? %>
<%# TAI aggiunto raw() %>
    <p><i class="icon-ok-sign"></i> <%= raw(t('count.fonds.success', :count => @fonds.count, :field => t('name'))) %></p>
  <% else %>
    <p data-toggle="collapse" data-target="#fonds-no-name">
<%# TAI aggiunto raw() %>
      <i class="icon-exclamation-sign"></i> <%= raw(t('count.fonds.failure', :count => @fonds_with_no_name.count,
        :total => @fonds.count,
        :percentage => number_to_percentage(@fonds_with_no_name.count.to_f/@fonds.count.to_f * 100,:precision => 2),
        :field => t('name'))) %>
    </p>
    <div id="fonds-no-name" class="collapse">
<%# Upgrade 2.0.0 inizio %>
      <%#= render :partial => "fond", :object => @fonds_with_no_name %>
      <%= render :partial => "fond", :object => @fonds_with_no_name, as: "object" %>
<%# Upgrade 2.0.0 fine %>
    </div>
  <% end %>

  <h4>2. <%= t('date_event') %></h4>
  <% if @fonds_with_no_event.count.zero? %>
<%# TAI aggiunto raw() %>
    <p><i class="icon-ok-sign"></i> <%= raw(t('count.fonds.success', :count => @fonds.count, :field => t('date_event'))) %></p>
  <% else %>
    <p data-toggle="collapse" data-target="#fonds-no-event">
<%# TAI aggiunto raw() %>
      <i class="icon-exclamation-sign"></i> <%= raw(t('count.fonds.failure', :count => @fonds_with_no_event.count,
        :total => @fonds.count,
        :percentage => number_to_percentage(@fonds_with_no_event.count.to_f/@fonds.count.to_f * 100,:precision => 2),
        :field => t('date_event'))) %>
    </p>
    <div id="fonds-no-event" class="collapse">
<%# Upgrade 2.0.0 inizio %>
      <%#= render :partial => "fond", :object => @fonds_with_no_event %>
      <%= render :partial => "fond", :object => @fonds_with_no_event, as: "object" %>
<%# Upgrade 2.0.0 fine %>
    </div>
  <% end %>

  <h4>3. <%= t('short_fond_type') %></h4>
  <% if @fonds_with_no_fond_type.count.zero? %>
<%# TAI aggiunto raw() %>
    <p><i class="icon-ok-sign"></i> <%= raw(t('count.fonds.success', :count => @fonds.count, :field => t('short_fond_type'))) %></p>
  <% else %>
    <p data-toggle="collapse" data-target="#fonds-no-type">
<%# TAI aggiunto raw() %>
      <i class="icon-exclamation-sign"></i> <%= raw(t('count.fonds.failure', :count => @fonds_with_no_fond_type.count,
        :total => @fonds.count,
        :percentage => number_to_percentage(@fonds_with_no_fond_type.count.to_f/@fonds.count.to_f * 100,:precision => 2),
        :field => t('short_fond_type'))) %>
    </p>
    <div id="fonds-no-type"  class="collapse">
<%# Upgrade 2.0.0 inizio %>
      <%#= render :partial => "fond", :object => @fonds_with_no_fond_type %>
      <%= render :partial => "fond", :object => @fonds_with_no_fond_type, as: "object" %>
<%# Upgrade 2.0.0 fine %>
    </div>
  <% end %>

<%# Upgrade 3.0.0 inizio %>
<%# Requisito minimo unità correlate %>
<h4>4. <%= t('short_units_count') %></h4>
  <% if @fonds_with_no_units.count.zero? %>
    <p><i class="icon-ok-sign"></i> <%= raw(t('count.units.success', :count => @fonds.count, :field => t('short_units_count'))) %></p>
  <% else %>
    <p data-toggle="collapse" data-target="#fonds-no-units">
      <i class="icon-exclamation-sign"></i> <%= raw(t('count.units.failure', :count => @fonds_with_no_units.count,
        :total => @fonds.count,
        :percentage => number_to_percentage(@fonds_with_no_units.count.to_f/@fonds.count.to_f * 100,:precision => 2),
        :field => t('short_units_count'))) %>
    </p>
    <div id="fonds-no-units"  class="collapse">
      <%= render :partial => "fond", :object => @fonds_with_no_units, as: "object" %>
    </div>
  <% end %>
<%# Upgrade 3.0.0 fine %>

  <h3 class="section">Requisiti medi</h3>
  <h4>1. <%= t('description') %> </h4>
  <% if @fonds_with_no_description.count.zero? %>
<%# TAI aggiunto raw() %>
    <p><i class="icon-ok-sign"></i> <%= raw(t('count.fonds.success', :count => @fonds.count, :field => t('description'))) %></p>
  <% else %>
    <p data-toggle="collapse" data-target="#fonds-no-description">
<%# TAI aggiunto raw() %>
      <i class="icon-exclamation-sign"></i> <%= raw(t('count.fonds.failure', :count => @fonds_with_no_description.count,
        :total => @fonds.count,
        :percentage => number_to_percentage(@fonds_with_no_description.count.to_f/@fonds.count.to_f * 100,
          :precision => 2),
        :field => t('description'))) %>
    <div id="fonds-no-description" class="collapse">
<%# Upgrade 2.0.0 inizio %>
      <%#= render :partial => "fond", :object => @fonds_with_no_description %>
      <%= render :partial => "fond", :object => @fonds_with_no_description, as: "object" %>
<%# Upgrade 2.0.0 fine %>
    </div>
  <% end %>

  <h4>2. <%= t('history')  %> </h4>
  <% if @fonds_with_no_history.count.zero? %>
<%# TAI aggiunto raw() %>
    <p><i class="icon-ok-sign"></i> <%= raw(t('count.fonds.success', :count => @fonds.count, :field => t('history'))) %></p>
  <% else %>
    <p data-toggle="collapse" data-target="#fonds-no-history">
<%# TAI aggiunto raw() %>
      <i class="icon-exclamation-sign"></i> <%= raw(t('count.fonds.failure', :count => @fonds_with_no_history.count,
        :total => @fonds.count,
        :percentage => number_to_percentage(@fonds_with_no_history.count.to_f/@fonds.count.to_f * 100,:precision => 2),
        :field =>  t('history'))) %>
    </p>
    <div id="fonds-no-history" class="collapse">
<%# Upgrade 2.0.0 inizio %>
      <%#= render :partial => "fond", :object => @fonds_with_no_history %>
      <%= render :partial => "fond", :object => @fonds_with_no_history, as: "object" %>
<%# Upgrade 2.0.0 fine %>
    </div>
  <% end %>

  <h4>3. <%= t('length') %></h4>
  <% if @fonds_with_no_length.count.zero? %>
<%# TAI aggiunto raw() %>
    <p><i class="icon-ok-sign"></i> <%= raw(t('count.fonds.success', :count => @fonds.count, :field => t('length'))) %></p>
  <% else %>
    <p data-toggle="collapse" data-target="#fonds-no-length">
<%# TAI aggiunto raw() %>
      <i class="icon-exclamation-sign"></i> <%= raw(t('count.fonds.failure', :count => @fonds_with_no_length.count,
        :total => @fonds.count,
        :percentage => number_to_percentage(@fonds_with_no_length.count.to_f/@fonds.count.to_f * 100,:precision => 2),
        :field =>  t('length'))) %>
    </p>
    <div id="fonds-no-length" class="collapse">
<%# Upgrade 2.0.0 inizio %>
      <%#= render :partial => "fond", :object => @fonds_with_no_length %>
      <%= render :partial => "fond", :object => @fonds_with_no_length, as: "object" %>
<%# Upgrade 2.0.0 fine %>
    </div>
  <% end %>

<%# Upgrade 3.0.0 inizio %>
<%# Aggiunta requisiti medi progetti e fonti %>
<h4>4. <%= t('projects') %></h4>
  <% if @projects.present? %>
      <p><%= raw(t('count.projects', :count => @projects.count)) %></p>
      <%= render :partial => "project", :collection => @projects %>
  <% else %>
    <p class="red">[Nessun progetto associato]</p>
  <% end %>

<h4>5. <%= t('sources') %></h4>
  <% if @fonds_with_sources.count.empty? %>
    <p><i class="icon-ok-sign"></i> <%= raw(t('count.sources', :count => @fonds_with_sources.length)) %></p>
  <% else %>
    <p data-toggle="collapse" data-target="#fonds-no-sources">
      <i class="icon-exclamation-sign"></i> <%= raw(t('count.sources', :count => @fonds_with_sources.length,
        :total => @fonds.count,
        :percentage => number_to_percentage(@fonds_with_sources.length/@fonds.count.to_f * 100,:precision => 2),
        :field =>  t('length'))) %>
    </p>
    <div id="fonds-no-sources" class="collapse">
      <%= render :partial => "fond", :object => @fonds_with_sources, as: "object" %>
    </div>
  <% end %>
<%# Upgrade 3.0.0 fine %>

  <h2>Soggetti produttori</h2>

  <% if @creators.present? %>
<%# TAI aggiunto raw() %>
    <p><%= raw(t('count.creators', :count => @creators.length)) %></p>
    <% unless @fonds.first.creators.present? %>
      <p class="red">[Nessun soggetto produttore associato al complesso archivistico di primo livello]</p>
    <% end %>
    <%= render :partial => 'creator', :collection => @creators, :locals => {:fond => params[:id]} %>
  <% else %>
    <p class="red">[Nessun soggetto produttore associato]</p>
  <% end %>

  <h2>Soggetti conservatori</h2>

  <% if @custodians.present? %>
<%# TAI aggiunto raw() %>
    <p><%= raw(t('count.custodians', :count => @custodians.count)) %></p>
    <%= render :partial => "custodian", :collection => @custodians %>
  <% else %>
    <p class="red">[Nessun soggetto conservatore associato]</p>
  <% end %>

</div>

app/views/quality_checks/index.html.erb
<% content_for :status_bar do %>
  <h2>Controllo qualità</h2>
<% end %>

<div class="span12">

<% if @fonds.size > 0 %>
  <h3>Complessi archivistici</h3>

  <% if @fonds.size < 5 %>
    <% @fonds.each do |fond| %>
      <p><%= link_to fond.name, fond_quality_check_path(fond) %></p>
    <% end %>
  <% else %>
    <%= render :partial => "form_fonds" %>
  <% end %>

  <h3>Soggetti produttori</h3>
  <% case @creators.size
  when 0 %>
    <p>Non sono presenti schede soggetto produttore.</p>
  <%  when 1..5 %>
    <%  @creators.each do |creator| %>
      <p><%= link_to creator.preferred_name.name, creator_quality_check_path(creator) %> </p>
    <% end %>
  <% else %>
    <%= render :partial => "form_creators" %>
  <% end %>

  <h3>Soggetti conservatori</h3>
  <% case @custodians.size
  when 0 %>
    <p>Non sono presenti schede soggetto conservatore.</p>
  <%  when 1..5 %>
    <%  @custodians.each do |custodian| %>
      <p><%= link_to custodian.preferred_name.name, custodian_quality_check_path(custodian) %> </p>
    <% end %>
  <% else %>
    <%= render :partial => "form_custodians" %>
  <% end %>

<% else %>
  <p>Non sono presenti schede complesso archivistico. Controllo qualità non disponibile.</p>
<% end %>

</div>