config/routes.rb
# Upgrade 2.0.0 inizio
Rails.application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resources :users do
    put 'toggle_active', on: :member
  end

  # Polymorphic resources (must be here, prior to parent resources)
  resources :digital_objects, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end
  resources :group_images, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end

  resources :groups do
    resources :group_carousel_images, :except => [:show, :destroy], :controller => "group_images", :type => "carousel"
    resources :group_logo_images, :except => [:show, :destroy], :controller => "group_images", :type => "logo"
  end

  resources :fonds, :except => [:new] do
    member do
      get    :tree
      get    :treeview
      put    :ajax_update
      patch  :ajax_update
      put    :rename
      put    :move
      get    :merge_with
      post   :merge
      get    :split_fond
      post   :split
      get    :trash
      get    :trashed_subtree
      put    :move_to_trash
      put    :restore_subtree
      delete :destroy_subtree
      put    :publish
      put    :unpublish
    end
    collection do
      get  :save_a_tree
      post :saving_the_tree
      get  :list
      post :ajax_create
    end

    resources :units do
      collection do
        get  :gridview
        post :gridview
        get  :grid
        post :add_rows
        put  :remove_rows
        put  :reorder_rows
# Upgrade 2.1.0 inizio
#        get  :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :units, :except => [:new] do
    member do
      put   :ajax_update
      patch :ajax_update
      get   :render_full_path
      get   :preferred_event
      get   :textfield_form
      put   :update_event
# Upgrade 2.1.0 inizio
#      get   :edit_iccd
#      get   :show_iccd
# Upgrade 2.1.0 fine
      get   :move
      post  :move_down
      post  :move_up
    end
    collection do
      get :list_oa_mtc
      get :list_oa_ogtd
      get :list_bdm_ogtd
      get :list_bdm_mtcm
      get :list_bdm_mtct
# Upgrade 2.1.0 inizio
      get :sc2_voc_list
# Upgrade 2.1.0 fine
      put :classify
    end

    # OPTIMIZE: rinominare in subunits ?
    resources :children, :controller => 'units', :only => 'new' do
      collection do
# Upgrade 2.1.0 inizio
#        get :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :creators do
    collection do 
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :custodians do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :sources do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :institutions do
    collection do
      get :list
    end
  end

  resources :document_forms do
    collection do
      get :list
    end
  end

  resources :projects do
    collection do
      get :list
      put :publish
      put :unpublish
    end
  end

  resources :editors do
    collection do
      get  :list
      get  :modal_new
      post :modal_create
    end
  end

  # Strumenti
  resources :headings do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :anagraphics do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :reports, :only => [:index] do
    member do
      get  :dashboard
      get  :summary
      get  :inventory
      post :inventory
      get  :creators
      get  :custodians
      get  :labels
      get  :units
      get  :custodian
      post :custodian
      get  :project
      post :project
    end
    collection do
      get :download
    end
  end

  resources :quality_checks, :only => [:index] do
    member do
      get :fond
      get :creator
      get :custodian
    end
  end

# Upgrade 3.0.0 inizio
resources :multiple_occours, :only => [:index] do
    member do
      post :merge
    end
  end
# Upgrade 3.0.0 fine

  resources :imports, :only => [:index, :new, :create, :destroy]
  resources :exports, :only => [:index] do
    collection do
      get :download
      get :xml
      get :fonds_aef
      get :units_ead
      # Upgrade 2.2.0 inizio
      post :units
      # Upgrade 2.2.0 fine
    end
  end
  resources :exports_batch, :only => [:index] do
    collection do
      post :icarimport
      post :aefallfonds
      post :aeffondsnoancestry
      post :aefallfondsnoancestry
      post :aefprojects
      post :aefallprojects
      post :aefcustodiansproject
      post :aefcustodians
      post :aefallcustodians
      post :xmlallfonds
      post :xmlfondsnoancestry
      post :xmlallfondsnoancestry
      post :xmlsourcesproject
      post :xmlsources
      post :xmlallsources
    end
  end    

  # Vocabolari
  resources :vocabularies, :only => [:index]

  resources :creator_corporate_types, :only => [:index]
  resources :custodian_types, :only => [:index]
  resources :source_types, :only => [:index]

  resources :activities, :only => [:index] do
    collection do
      get :list
    end
  end
  resources :places, :only => [:index] do
    collection do
      get :cities
      get :countries
    end
  end
  resources :langs, :only => [:index]

  # Non-Resourceful Routes
  root :to => 'site#dashboard'
  resources :about, :only => [:index], :to => "site#about"
  match :parse_textile, :only => [:index], :to => "site#parse_textile", :via => [:get, :post]

end

# Upgrade 2.0.0 fine

app/views/shared/_devise_status.html.erb
<% if user_signed_in? %>
  <p class="navbar-text pull-right">
    <em><%= t('devise.user') %></em>: <%= link_to(current_user.username, edit_user_path(current_user)) %>
    <span style="padding: 0 4px">|</span>
    <%= link_to(t('devise.sessions.sign_out'), destroy_user_session_path, :method => :delete) %>
  </p>
<% end %>

app/views/shared/_editor.html.erb
<div class="row fields">
  <div class="span2">
<%# Upgrade 2.2.0 inizio %>
    <%#= f.text_field :name, :id => "fond-editor-name-autocomplete", :class => "autocomplete span2", :'data-autocompletion-controller' => 'editors' %>
    <%= f.text_field :name, :id => "fond-editor-name-autocomplete", :class => "autocomplete span2",
        :'data-autocompletion-controller' => 'editors',
        :'data-autocompletion-group-filter' => if current_user.is_multi_group_user?() then current_ability.target_group_id.to_s else '' end
    %>
<%# Upgrade 2.2.0 fine %>
  </div>
  <div class="span2">
    <%= f.text_field :qualifier, :class => "span2" %>
  </div>
  <div class="span2">
    <%= terms_select(f, "editors.editing_type", {:prompt => true}, :class => "span2") %>
  </div>
  <div class="span2">
    <%= f.text_field :edited_at, { :class => "span2 datepicker" } %>
  </div>
  <div class="span1 destroy">
    <%= f.check_box :_destroy %> <%= f.label :_destroy, t('destroy') %>
  </div>
</div>

app/views/shared/_editors_labels.html.erb
<div class="row row-labels">
  <div class="span2"><%= t('fond_editor') %></div>
  <div class="span2"><%= t('qualifier') %></div>
  <div class="span2"><%= t('editing_type') %></div>
  <div class="span2"><%= t('edited_at') %></div>
</div>

app/views/shared/_generic_error_message.html.erb
<% if object.errors.any? %>
<div class="span9">
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">×</a>
    <%= t('activerecord.generic_record_invalid') %>
    <%# OPTIMIZE: aggiungere errors di events %>
<%# Upgrade 2.1.0 inizio %>
    <ul>
      <% object.errors.each do |key, message| %>
        <li><%= t(key) %></li>
        <li><%= message.to_s %></li>
      <% end %>
    </ul>
<%# Upgrade 2.1.0 fine %>
  </div>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
<div class="navbar-inner">
<div class="container-fluid">

<ul class="nav">
  <li<%= active_if(controller_name == "site" && action_name == "dashboard") %>>
  <%= link_to t('dashboard'), root_path %></li>
  <li class="dropdown" id="nav-descriptions">
<%# TAI aggiunto raw() %>
    <%#= link_to 'Schede <b class="caret"></b>', "#nav-descriptions", :class => "dropdown-toggle", :'data-toggle' => "dropdown" %>
    <%= link_to raw('Schede <b class="caret"></b>'), "#nav-descriptions", :class => "dropdown-toggle", :'data-toggle' => "dropdown" %>
    <ul class="dropdown-menu">
      <li><%= link_to t('fonds'), fonds_path %></li>
      <li><%= link_to t('creators'), creators_path %></li>
      <li><%= link_to t('custodians'), custodians_path %></li>
      <li class="divider"></li>
      <li><%= link_to t('sources'), sources_path %></li>
      <li><%= link_to t('digital_objects'), IM_ENABLED ? all_digital_objects_path : disabled_digital_objects_path %></li>
      <li class="divider"></li>
      <li><%= link_to t('institutions'), institutions_path %></li>
      <li><%= link_to t('document_forms'), document_forms_path %></li>
      <li class="divider"></li>
      <li><%= link_to t('projects'), projects_path %></li>
      <li><%= link_to t('editors'), editors_path %></li>
    </ul>
  </li>
  <li class="dropdown" id="nav-tools">
<%# TAI aggiunto raw() %>
    <%#= link_to 'Strumenti <b class="caret"></b>', "#nav-tools", :class => "dropdown-toggle", :'data-toggle' => "dropdown" %>
    <%= link_to raw('Strumenti <b class="caret"></b>'), "#nav-tools", :class => "dropdown-toggle", :'data-toggle' => "dropdown" %>
    <ul class="dropdown-menu">
      <li><%= link_to t('headings'), headings_path %></li>
      <li><%= link_to t('personal_details'), anagraphics_path %></li> <%# link a schede anagrafiche %>
      <li class="divider"></li>
<%# TAI aggiunto raw() %>
      <li><%= link_to raw("Controllo qualità&hellip;"), quality_checks_path %></li>
<%# TAI aggiunto raw() %>
      <li><%= link_to raw("Report&hellip;"), reports_path %></li>
<%# Upgrade 3.0.0 Inizio %>
<%# TAI aggiunto raw()  per nuovo Strumento Occorrenze Multiple %>
      <li><%= link_to raw("Occorrenze Multiple&hellip;"), multiple_occours_path %></li>
<%# Upgrade 3.0.0 Fine %>
      <li class="divider"></li>
<%# TAI aggiunto raw() %>
      <li><%= link_to raw("Importa&hellip;"), imports_path %></li>
<%# TAI aggiunto raw() %>
      <li><%= link_to raw("Esporta&hellip;"), exports_path %></li>
      <li><%= link_to raw("Esportazione batch&hellip;"), exports_batch_index_path %></li>
      <% if current_user.is_superadmin? %>
        <li class="divider"></li>
        <li><%= link_to "Gestione utenti", users_path %></li>
        <li><%= link_to "Gestione gruppi", groups_path %></li>
      <% end %>
<%# Upgrade 2.2.0 inizio %>
      <%# if current_user.is_admin? %>
      <% if current_user.is_admin_for_some_group? %>
<%# Upgrade 2.2.0 fine %>
        <li class="divider"></li>
        <li><%= link_to "Gestione utenti", users_path %></li>
<%# Upgrade 2.1.0 inizio %>
        <% if current_ability.can?(:manage, Group) %>
          <li><%= link_to "Gestione gruppi", groups_path %></li>
        <% end %>
<%# Upgrade 2.1.0 end %>
      <% end %>
    </ul>
  </li>
  <li<%= active_if(controller_name == "vocabularies") %>><%= link_to 'Vocabolari', vocabularies_path %></li>
</ul>

  <%= render :partial => "shared/devise_status" %>

</div>
</div>
</div>

app/views/shared/_show_editors.html.erb
<h3 class="section"><%= t('editors') %></h3>
<table class="table-show">
  <tr>
    <th><%= t('editors') %></th>
    <td>
      <% if object.present? %>
        <ul>
          <% object.each do |editor| %>
            <li><%= show_editor(editor) %></li>
          <% end %>
        </ul>
      <%  else %>
        <%= blank_field %>
      <% end %>
    </td>
  </tr>
</table>

app/views/shared/_show_sources.html.erb
<h3 class="section"><%= t('sources_area') %></h3>
<table class="table-show">
  <tr>
    <th><%= t('sources') %></th>
    <td>
      <% if object.present? %>
        <ul>
          <% object.each do |source| %>
            <li><%= source.short_title %> = <%= formatted_source(source) %></li>
          <% end %>
        </ul>
      <%  else %>
        <%= blank_field %>
      <% end %>
    </td>
  </tr>
</table>

app/views/shared/_side.html.erb
<div id="record-side" class="span3">
  <div class="well"  style="padding-top: 5px; padding-bottom: 5px;">
    <div id="side-primary-actions" class="clearfix">
      <% if action_name == "show" %>
        <%= link_to t('edit'), edit_object_path(object), :class => "btn pull-left" %>
      <% elsif action_name == "show_iccd" %>
        <%= link_to t('edit'), edit_iccd_unit_path(@unit, :t => "#{@unit.tsk}"), :class => "btn pull-left" %>
      <% elsif action_name == "edit_iccd" %>
        <%= submit_tag " " + t('save_and_continue') + " ", :name => "save_and_continue_iccd", :class => "btn btn-primary pull-left" %>
      <% else %>
        <%= submit_tag " " + t('save_and_continue') + " ", :name => "save_and_continue", :class => "btn btn-primary pull-left" %>
      <% end %>

      <% unless %w[new create].include?(action_name) %>
        <% if controller_name == "fonds" %>
<%# Upgrade 2.0.0 inizio %>
          <%#= link_to_unless(@descendant_units_count > 0, t('destroy'), object, :confirm => t('are_you_sure'), :method => :delete, :class => "destroy-link pull-right") do |name| raw("<span class='muted destroy-link pull-right' title='Per poter eliminare il complesso devi prima eliminare le unità collegate al complesso o ai complessi discendenti.'>#{name}</span>") end %>
          <%= link_to_unless(@descendant_units_count > 0, t('destroy'), object, data: {:confirm => t('are_you_sure')}, :method => :delete, :class => "destroy-link pull-right") do |name| raw("<span class='muted destroy-link pull-right' title='Per poter eliminare il complesso devi prima eliminare le unità collegate al complesso o ai complessi discendenti.'>#{name}</span>") end %>
<%# Upgrade 2.0.0 fine %>
        <% else %>
<%# Upgrade 2.1.0 inizio %>
          <%#= link_to t('destroy'), object, :confirm => t('are_you_sure'), :method => :delete, :class => "destroy-link pull-right" %>
          <% if controller_name == "group_images" %>
            <%= link_to t('destroy'), group_image_path(object), data: { :confirm => t('are_you_sure')}, :method => :delete, :class => "destroy-link pull-right" %>
          <% else %>
            <%= link_to t('destroy'), object, data: { :confirm => t('are_you_sure')}, :method => :delete, :class => "destroy-link pull-right" %>
          <% end %>
<%# Upgrade 2.1.0 fine %>
        <% end %>
      <% end %>
    </div>
    <hr />

<%# NOTE: dubbio che vada bene qui e non nella status-bar come prima %>
    <% if controller_name == "units" %>
      <% if %w[edit update show edit_iccd update_iccd show_iccd].include?(action_name) %>
        <div id="side-nav" class="clearfix">
          <%= prev_or_next_link("left", @unit.prev_in_sequence, action_name) %>
          <span class="nav-counter">
            <%= number_with_delimiter(@unit.sequence_number) %> di <%= number_with_delimiter(@root_fond.active_descendant_units_count) %>
          </span>
          <%= prev_or_next_link("right", @unit.next_in_sequence, action_name) %>
        </div>
        <hr />
      <% end %>

      <div>
        <p><strong><%= @unit.level_type %></strong></p>
        <% unless @unit.is_root? %>
          <p>Fa parte di:<br />
            <% @unit.ancestors.each do |ancestor| %>
              <%= link_to ancestor.title, edit_unit_path(ancestor) %> &gt;
            <% end %>
          <% end %>
        </p>
      </div>
      <hr />
    <% end %>

<%# Upgrade 2.1.0 inizio %>
<%# aggiunto group_images %>
<%# Upgrade 2.1.0 fine %>
    <% if (controller_name != "digital_objects") && (controller_name != "group_images") && (action_name != "show") && (action_name != "show_iccd") %>
      <div id="side-secondary-actions" class="clearfix">
        <% if %w[new_iccd edit_iccd show_iccd].include?(action_name) %>
          <%= submit_tag t('preview'), :name => "show_iccd", :class => "btn btn-small pull-left" %>
        <% else %>
          <%= submit_tag t('preview'), :class => "btn btn-small pull-left" %>
        <% end %>
  <%# FIXME - DRY %>
        <% if controller_name == "units" %>
          <% if @unit.new_record? %>
            <%= submit_tag "+ " + t('new'), :class => "btn btn-small pull-right disabled" %>
          <% else %>
            <% if %w[new_iccd edit_iccd show_iccd].include?(action_name) == true %>
              <%= submit_tag "+ " + t('new'), :name => "save_and_add_new_iccd", :class => "btn btn-small pull-right" %>
            <% else %>
              <%= submit_tag "+ " + t('new'), :name => "save_and_add_new", :class => "btn btn-small pull-right" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
  <%# FIXME - dirty %>
      <% unless (controller_name == "sources") %>
        <hr />
      <% end %>
    <% end %>

    <% if controller_name =="sources" && %w[edit update].include?(action_name) %>
      <% if @source.db_source.present? %>
        <p><strong>Descrizione importata</strong></p>
        <p><em>ID</em>: <%= @source.legacy_id %><br />
          <em>Descrizione</em>: <%= h @source.legacy_description %></p>
      <% end %>
      <% if @source.legacy_authors.present? %>
        <p><em>Autori / curatori</em>:</p>
        <ul>
          <% @source.legacy_authors.split("#").each do |la| %>
            <li><%= la %></li>
          <% end %>
        </ul>
      <% end %>
      <% if @source.db_source.present? || @source.legacy_authors.present? %>
        <hr />
      <% end %>
    <% end %>

    <% if controller_name =="units" && %w[new_iccd edit_iccd].include?(action_name) %>
      <% if @unit.new_record? %>
        <% target_link = @unit.is_root? ? new_fond_unit_path : new_unit_child_path %>
        Vai alla <%= link_to 'scheda normale', target_link %>
      <% else %>
        Vai alla <%= link_to 'scheda normale', edit_unit_path(@unit, :t => @unit.tsk) %>
      <% end %>
      <hr />
    <% end %>

<%# Upgrade 2.1.0 inizio %>
<% if false %>
    <% if controller_name == "units" && %w[new edit].include?(action_name) %>
      <% if @unit.new_record? %>
        <% target_link = @unit.is_root? ? new_iccd_fond_units_path : new_iccd_unit_children_path %>
        Vai alla <%= link_to 'scheda speciale', target_link %>
      <% else %>
        Vai alla <%= link_to 'scheda speciale', edit_iccd_unit_path(@unit, :t => @unit.tsk) %>
      <% end %>
      <hr />
    <% end %>
<% end %>
<%# Upgrade 2.1.0 fine %>

    <div id="side-meta">
      <% if object.new_record? %>
        <%= t('unsaved_record') %>
      <% else %>
        <dl id="updater">
          <dt><%= t('updated_by') %></dt>
          <dd><%= object.updater.full_name %></dd>
          <dt><%= t('updated_at') %></dt>
          <dd><%= l object.updated_at, :format => :long %></dd>
        </dl>
      <% end %>
    </div>

  </div> <%# /well %>

<%# digital_objects %>
  <% if %w[fonds units creators custodians sources].include?(controller_name) %>
    <% if IM_ENABLED %>
      <div class="well" style="padding-top: 5px; padding-bottom: 5px;">
        <% if %w[new create new_iccd].include?(action_name) %>
          <span class="muted"><%= t('digital_objects') %></span>
        <% else %>
          <%= link_to_digital_objects_by_count(object.digital_objects.count, t('digital_objects'), object) %>
          <%= link_to_digital_objects_by_count(object.digital_objects.count, object.digital_objects.count, object, :class => "badge") unless object.digital_objects.count == 0 %>
        <% end %>
      </div>
    <% else %>
      <div id="digital-objects-warning" class="well">
        <span class="muted"><%= t('digital_objects') %></span>
      </div>
    <% end %>
  <% end %>

  <%# anagraphics %>
  <% if %w[units].include?(controller_name) %>
    <div class="well" id="anagraphic" style="padding-top: 5px; padding-bottom: 5px;" >
      <% if %w[new create].include?(action_name) %>
        <span class="muted"><%= t('anagraphics') %></span>
      <% else %>
        <h3><%= t('anagraphics') %></h3>
        <div>
          <p>
            <%= link_to t('new_anagraphic'), "#",
              {:id => "add-anagraphic-modal", :class => "btn btn-mini new",
              :'data-id' => object.id, :'data-controller' => controller_name} %>
            <%= link_to t('link_anagraphic'), "#",
              {:id => "link-anagraphic-modal", :class => "btn btn-mini",
              :'data-id' => object.id, :'data-controller' => controller_name} %>
          </p>
          <div style="overflow-y: auto; max-height:180px; background: #fff;" id="anagraphic-list" data-id="<%= object.id %>" data-controller="<%= controller_name %>"></div>
        </div>
      <% end %>
    </div>
  <% end %>

<%# headings %>
  <% if %w[fonds units].include?(controller_name) %>
    <div class="well" id="heading" style="padding-top: 5px; padding-bottom: 5px;" >
      <% if %w[new create].include?(action_name) %>
        <span class="muted"><%= t('headings') %></span>
      <% else %>
        <h3><%= t('headings') %></h3>
        <div>
          <p>
            <%= link_to t('new_heading'), "#",
              {:id => "add-heading-modal", :class => "btn btn-mini new",
              :'data-id' => object.id, :'data-controller' => controller_name} %>
            <%= link_to t('link_heading'), "#",
              {:id => "link-heading-modal", :class => "btn btn-mini",
              :'data-id' => object.id, :'data-controller' => controller_name} %>
          </p>
          <div style="overflow-y: auto; max-height:180px; background: #fff;" id="heading-list" data-id="<%= object.id %>" data-controller="<%= controller_name %>"></div>
        </div>
      <% end %>
    </div>
  <% end %>

</div> <%# /record-side %>