config/routes.rb
# Upgrade 2.0.0 inizio
Rails.application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resources :users do
    put 'toggle_active', on: :member
  end

  # Polymorphic resources (must be here, prior to parent resources)
  resources :digital_objects, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end
  resources :group_images, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end

  resources :groups do
    resources :group_carousel_images, :except => [:show, :destroy], :controller => "group_images", :type => "carousel"
    resources :group_logo_images, :except => [:show, :destroy], :controller => "group_images", :type => "logo"
  end

  resources :fonds, :except => [:new] do
    member do
      get    :tree
      get    :treeview
      put    :ajax_update
      patch  :ajax_update
      put    :rename
      put    :move
      get    :merge_with
      post   :merge
      get    :split_fond
      post   :split
      get    :trash
      get    :trashed_subtree
      put    :move_to_trash
      put    :restore_subtree
      delete :destroy_subtree
      put    :publish
      put    :unpublish
    end
    collection do
      get  :save_a_tree
      post :saving_the_tree
      get  :list
      post :ajax_create
    end

    resources :units do
      collection do
        get  :gridview
        post :gridview
        get  :grid
        post :add_rows
        put  :remove_rows
        put  :reorder_rows
# Upgrade 2.1.0 inizio
#        get  :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :units, :except => [:new] do
    member do
      put   :ajax_update
      patch :ajax_update
      get   :render_full_path
      get   :preferred_event
      get   :textfield_form
      put   :update_event
# Upgrade 2.1.0 inizio
#      get   :edit_iccd
#      get   :show_iccd
# Upgrade 2.1.0 fine
      get   :move
      post  :move_down
      post  :move_up
    end
    collection do
      get :list_oa_mtc
      get :list_oa_ogtd
      get :list_bdm_ogtd
      get :list_bdm_mtcm
      get :list_bdm_mtct
# Upgrade 2.1.0 inizio
      get :sc2_voc_list
# Upgrade 2.1.0 fine
      put :classify
    end

    # OPTIMIZE: rinominare in subunits ?
    resources :children, :controller => 'units', :only => 'new' do
      collection do
# Upgrade 2.1.0 inizio
#        get :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :creators do
    collection do 
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :custodians do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :sources do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :institutions do
    collection do
      get :list
    end
  end

  resources :document_forms do
    collection do
      get :list
    end
  end

  resources :projects do
    collection do
      get :list
      put :publish
      put :unpublish
    end
  end

  resources :editors do
    collection do
      get  :list
      get  :modal_new
      post :modal_create
    end
  end

  # Strumenti
  resources :headings do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :anagraphics do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :reports, :only => [:index] do
    member do
      get  :dashboard
      get  :summary
      get  :inventory
      post :inventory
      get  :creators
      get  :custodians
      get  :labels
      get  :units
      get  :custodian
      post :custodian
      get  :project
      post :project
    end
    collection do
      get :download
    end
  end

  resources :quality_checks, :only => [:index] do
    member do
      get :fond
      get :creator
      get :custodian
    end
  end

# Upgrade 3.0.0 inizio
resources :multiple_occours, :only => [:index] do
    member do
      post :merge
    end
  end
# Upgrade 3.0.0 fine

  resources :imports, :only => [:index, :new, :create, :destroy]
  resources :exports, :only => [:index] do
    collection do
      get :download
      get :xml
      get :fonds_aef
      get :units_ead
      # Upgrade 2.2.0 inizio
      post :units
      # Upgrade 2.2.0 fine
    end
  end
  resources :exports_batch, :only => [:index] do
    collection do
      post :icarimport
      post :aefallfonds
      post :aeffondsnoancestry
      post :aefallfondsnoancestry
      post :aefprojects
      post :aefallprojects
      post :aefcustodiansproject
      post :aefcustodians
      post :aefallcustodians
      post :xmlallfonds
      post :xmlfondsnoancestry
      post :xmlallfondsnoancestry
      post :xmlsourcesproject
      post :xmlsources
      post :xmlallsources
    end
  end    

  # Vocabolari
  resources :vocabularies, :only => [:index]

  resources :creator_corporate_types, :only => [:index]
  resources :custodian_types, :only => [:index]
  resources :source_types, :only => [:index]

  resources :activities, :only => [:index] do
    collection do
      get :list
    end
  end
  resources :places, :only => [:index] do
    collection do
      get :cities
      get :countries
    end
  end
  resources :langs, :only => [:index]

  # Non-Resourceful Routes
  root :to => 'site#dashboard'
  resources :about, :only => [:index], :to => "site#about"
  match :parse_textile, :only => [:index], :to => "site#parse_textile", :via => [:get, :post]

end

# Upgrade 2.0.0 fine

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  helper_method :sort_column
  load_and_authorize_resource
# Upgrade 2.2.0 inizio
  skip_load_and_authorize_resource :only => [ :list ]
# Upgrade 2.2.0 fine

# Upgrade 2.2.0 inizio
  def current_ability
    if @current_ability.nil?
      if (current_user.is_multi_group_user?())
        if (["show","edit","update","destroy"].include?(params[:action]))
          c = Creator.select("group_id").find(params[:id])
          @current_ability ||= Ability.new(current_user, c.group_id)
        elsif (["list"].include?(params[:action]))
          group_id = str2int(params[:group_id])
          @current_ability ||= Ability.new(current_user, group_id)
        elsif (["index"].include?(params[:action]))
          @current_ability ||= Ability.new(current_user, -1)
        elsif (["new","create"].include?(params[:action]))
          if params[:group_id].present?
            group_id = str2int(params[:group_id])
            @current_ability ||= Ability.new(current_user, group_id)
          end
        end
      end
    end
    if @current_ability.nil?
      @current_ability = super
    end
    return @current_ability
  end
# Upgrade 2.2.0 fine

  def index
# Upgrade 2.0.0 inizio
=begin
    @creators = Creator.list.search(params[:q]).accessible_by(current_ability, :read).paginate(:page => params[:page],
      :order => sort_column + ' ' + sort_direction,
      :include => :preferred_event)
=end
# Upgrade 2.2.0 inizio
=begin
    @creators = Creator.list.search(params[:q]).accessible_by(current_ability, :read).
      order(sort_column + ' ' + sort_direction).
      includes(:preferred_event).page(params[:page])
=end
    @creators = Creator.list.search(params[:q]).accessible_by(current_ability, :read).
      order(sort_column + ' ' + sort_direction).
      includes(:preferred_event,:projects).page(params[:page])
# Upgrade 2.2.0 fine
# Upgrade 2.0.0 fine
  end

  def list
    search_param  = [params[:term], params[:q]].find(&:present?)
    @creators = Creator.accessible_by(current_ability, :read).autocomplete_list(search_param)

    ActiveRecord::Base.include_root_in_json = false
    results = @creators.to_json(:methods => [:id, :value], :only => :methods)

    respond_to do |format|
      format.json { render :json => results }
    end
  end

  def show
    @creator = Creator.find(params[:id])
  end

  def new
    terms
    @creator = Creator.new
    params[:type] ||= 'C'
    @events = @creator.events_for_view
    setup_relation_collections
  end

  def edit
    @creator = Creator.find(params[:id])
    terms
    @events = @creator.events_for_view
    setup_relation_collections
  end

  def create
# Upgrade 2.0.0 inizio Strong parameters
#    @creator = Creator.new(params[:creator]).tap do |creator|
    @creator = Creator.new(creator_params).tap do |creator|
# Upgrade 2.0.0 fine
      creator.created_by = current_user.id
      creator.updated_by = current_user.id
# Upgrade 2.2.0 inizio
#      creator.group_id = current_user.group_id
        if current_user.is_multi_group_user?()
          creator.group_id = current_ability.target_group_id
        else
          creator.group_id = current_user.rel_user_groups[0].group_id
        end
# Upgrade 2.2.0 fine
    end
    @events = @creator.events.sort_by(&:order_date)
    @creator.save

    setup_relation_collections  # must be called after validation, otherwise records
    # marked for destruction won't be processed
    if @creator.valid?
      if params[:save_and_continue]
        redirect_to(edit_creator_url(@creator), :notice => 'Scheda creata')
      else
        redirect_to(@creator, :notice => 'Scheda creata')
      end
    else
      terms
      @events = @creator.events_for_view if @events.empty?
      render :action => "new"
    end
  end

  def update
    @creator = Creator.find(params[:id]).tap {|creator| creator.updated_by = current_user.id }
    @events = @creator.events.sort_by(&:order_date)
# Upgrade 2.0.0 inizio Strong parameters
#    @creator.update_attributes(params[:creator])
    @creator.update_attributes(creator_params)
# Upgrade 2.0.0 fine
    setup_relation_collections  # must be called after validation, otherwise records
    # marked for destruction won't be processed

    if @creator.valid?
      if params[:save_and_continue]
        redirect_to(edit_creator_url(@creator), :notice => 'Scheda aggiornata')
      else
        redirect_to(@creator)
      end
    else
      terms
      @events = @creator.events_for_view if @events.empty?
      render :action => "edit"
    end
  end

  def destroy
    @creator = Creator.find(params[:id])
    @creator.destroy

    redirect_to(creators_url, :notice => "Scheda eliminata")
  end

  private

  def setup_relation_collections
    return unless @creator

# Upgrade 2.0.0 inizio
=begin
    relation_collections  :related => "fonds", :through => "rel_creator_fonds",
      :available => Fond.accessible_by(current_ability, :read).roots.active.count('id'),
      :suggested => Proc.new{ Fond.roots.active.all( :select => 'id, name', :order => "name" ) }
=end
    relation_collections  :related => "fonds", :through => "rel_creator_fonds",
      :available => Fond.accessible_by(current_ability, :read).roots.active.count('id'),
      :suggested => Proc.new{ Fond.roots.active.select('id, name').order("name" ) }
# Upgrade 2.0.0 fine

# Upgrade 2.0.0 inizio
=begin
    relation_collections  :related => "institutions", :through => "rel_creator_institutions",
      :available => Institution.accessible_by(current_ability, :read).count('id'),
      :suggested => Proc.new{ Institution.accessible_by(current_ability, :read).all(:select => 'id, name', :order => 'name') }
=end
    relation_collections  :related => "institutions", :through => "rel_creator_institutions",
      :available => Institution.accessible_by(current_ability, :read).count('id'),
      :suggested => Proc.new{ Institution.accessible_by(current_ability, :read).select('id, name').order('name') }
# Upgrade 2.0.0 fine

    relation_collections  :related => "related_creators", :through => "rel_creator_creators",
      :available => Creator.accessible_by(current_ability, :read).count('id'),
      :suggested => Proc.new{ Creator.accessible_by(current_ability, :read).sorted_suggested }

    relation_collections  :related => "sources", :through => "rel_creator_sources"

# Upgrade 2.0.0 inizio
#    @association_types = CreatorAssociationType.all(:select => 'id, association_type', :order => 'id')
    @association_types = CreatorAssociationType.select('id, association_type').order('id')
# Upgrade 2.0.0 fine
  end

  def sort_column
# Upgrade 2.2.0 inizio
#    params[:sort] || "name"
    params[:sort] || "creator_names.name"
# Upgrade 2.2.0 fine
  end

# Upgrade 2.0.0 inizio Strong parameters
  private
    def creator_params
      params.require(:creator).permit!
    end
# Upgrade 2.0.0 fine

end

app/views/creators/_creator_activity.html.erb
<div class="fields row">
  <div class="span4">
  <%#= f.text_field  :activity,
                    :class => "autocomplete span4",
                    :'data-autocompletion-controller' => "activities",
                    :'data-autocompletion-action' => 'list' %>
  <%= f.text_field :activity, :class => "span4" %>
  </div>
  <div class="span4">
    <%= f.text_field :note, :class => "span4" %>
  </div>
  <div class="span1 destroy">
    <%= f.check_box :_destroy %> <%= f.label :_destroy, t('destroy') %>
  </div>
</div>

app/views/creators/_creator_identifier.html.erb
<div class="fields row">
  <div class="span3">
    <%= f.text_field :identifier, :class => "span3" %>
  </div>
  <div class="span2">
    <%= f.text_field :identifier_source, :class => "span2" %>
  </div>
  <div class="span3">
    <%= f.text_field :note, :class => "span3" %>
  </div>
  <div class="span1 destroy">
    <%= f.check_box :_destroy %> <%= f.label :_destroy, t('destroy') %>
  </div>
</div>

app/views/creators/_creator_legal_status.html.erb
<div class="fields row">
  <div class="span3">
    <%= terms_select(f, "creator_legal_statuses.legal_status", {:include_blank => true}, :class => "span3") %> 
  </div>
  <div class="span5"><%= f.text_field :note, :class => "span5" %></div>                     
  <div class="destroy span1"><%= f.check_box :_destroy %> <%= f.label :_destroy, t('destroy') %></div>
</div>

app/views/creators/_creator_name_cf.html.erb
<div class="fields row">
  <div class="span6">
    <%= f.hidden_field :preferred, :value => f.object.preferred %>
    <%= f.text_field :name, :class => "span6" %>
  </div>
  <div class="span3">
    <% n = f.object.note || f.object.note_cf %>
    <%= f.text_field :note_cf, :value => n, :class => "span3" %>
  </div>
</div>

app/views/creators/_creator_name_p.html.erb
<div class="fields row">
  <div class="span3">
    <%= f.hidden_field :preferred, :value => f.object.preferred %>
    <%= f.text_field :first_name %>
  </div>
  <div class="span3">
    <%= f.text_field :last_name %>
  </div>
  <div class="span3">
    <% n = f.object.note || f.object.note_p %>
    <%= f.text_field :note_p, :value => n %>
  </div>
</div>

app/views/creators/_creator_url.html.erb
<div class="fields row">
  <div class="span5"> 
    <%= f.text_field :url, :class => "span5" %>
  </div>
  <div class="span3">
    <%= f.text_field :note, :class => "span3" %>
  </div>
  <div class="span1 destroy">
    <%= f.check_box :_destroy %> <%= f.label :_destroy, t('destroy') %>
  </div>
</div>

app/views/creators/edit.html.erb
<% content_for :status_bar do %>
  <h2><%= status_bar_context %></h2>
  <div id="links">
    <%= link_to_index t('index_creators'), creators_path %>
  </div>
<% end %>

<%= render :partial => "form" %>

app/views/creators/index.html.erb
<% content_for :status_bar do %>
  <h2><%= status_bar_context %></h2>
<% end %>

<div class="span12">
  <div id="index-controls" class="clearfix">
<%# Upgrade 2.2.0 inizio %>
    <%# if @creators.total_entries > Creator.per_page || params[:q].present? %>
    <% if true %>
<%# Upgrade 2.2.0 fine %>
<%# TAI aggiunto = prima di form_tag %>
      <%= form_tag('/creators', :method => :get, :class => "skip-prompt form-search pull-right", :style => "margin-bottom: 0") do %>
        <%= text_field_tag :q, params[:q], :class => "search-query", :placeholder => "Denominazione" %>
        <%= submit_tag "Cerca", :name => "", :class => "btn btn-small" %>
      <% end %>
    <% end %>
    <div class="btn-group pull-left">
<%# Upgrade 2.2.0 inizio %>
      <% if current_user.is_multi_group_user?() %>
        <%= link_to raw(t('new') + '&nbsp;&nbsp;&nbsp;'), "#add_creator_modal", { :"data-toggle" => "modal", :class => "btn btn-mini new" } %>
      <% else %>
<%# Upgrade 2.0.0 inizio %>
        <%#= link_to t('new') + '<span class="caret"></span>', "#", { :class => "btn btn-small dropdown-toggle new", :'data-toggle' => "dropdown" } %>
        <%= link_to raw(t('new') + '<span class="caret"></span>'), "#", { :class => "btn btn-small dropdown-toggle new", :'data-toggle' => "dropdown" } %>
<%# Upgrade 2.0.0 fine %>
        <ul class="dropdown-menu">
          <li><%= link_to t('C'), new_creator_path(:type => "C") %></li>
          <li><%= link_to t('P'), new_creator_path(:type => "P") %></li>
          <li><%= link_to t('F'), new_creator_path(:type => "F") %></li>
        </ul>
      <% end %>
<%# Upgrade 2.2.0 fine %>
    </div>
  </div>

  <% if @creators.size > 0 %>
  <%= display_page_entries_info @creators %>
  <table class="table table-sortable">
    <thead>
      <tr>
<%# cambiato nome campo da name a creator_names.name %>
        <th><%= sortable("creator_names.name", t('creator_name')) %></th>
        <%# Upgrade 3.0.0 inizio %>
<%# aggiunta colonna per stato pubblicazione %>
          <th>&nbsp;</th>
<%# Upgrade 3.0.0 fine %>
        <th><%= sortable("creator_type", t('creator_type')) %></th>
<%# Upgrade 2.2.0 inizio %>
        <% if current_user.is_multi_group_user?() || current_user.is_superadmin?() %>
          <th class="span2"><%= sortable("groups.short_name", t('list_group_short_name')) %></th>
        <% end %>
<%# Upgrade 2.2.0 fine %>
        <th><%= sortable("creators.updated_at", t('updated_at')) %></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
    <% @creators.each do |creator| %>
      <tr class="<%= cycle("odd", "even") %>">
        <td>
            <%= creator.residence + ", " if creator.residence.present? %>
            <%= link_to creator.name, edit_creator_path(creator) %>
            <%= creator.preferred_event.try(:full_display_date) %>
            
<%# Upgrade 2.2.0 inizio %>
            <div class="index-item-info">
              <% if creator.projects.present? %>
                <%= t('projects') %>
                <ul class="index-item-list">
                  <% creator.projects.each do |project| %>
                    <li><%= link_to "#{project.name}", edit_project_path(project) %> <%= project.display_date %></li>
                  <% end %>
                </ul>
              <% end %>
            </div>
<%# Upgrade 2.2.0 fine %>
            
        </td>
<%# aggiunta visualizzazione stato pubblicazione %>
        <td><%= if creator.published == true then t('published') else  t('unpublished') end %></td>
<%# Upgrade 3.0.0 fine %>           
        <td><%= show_value(creator.creator_type, "t") %></td>

<%# Upgrade 2.2.0 inizio %>
        <% if current_user.is_multi_group_user?() || current_user.is_superadmin?() %>
          <td style="font-size: 11px;"><%= creator.group.short_name %></td>
        <% end %>
<%# Upgrade 2.2.0 fine %>

        <td><%= l creator.updated_at, :format => :long %></td>
        <td><%= link_to t('show'), creator %></td>
        <td>
<%# Upgrade 2.0.0 inizio %>
          <%#= link_to t('destroy'), creator, :confirm => t('are_you_sure'), :method => :delete %>
          <%= link_to t('destroy'), creator, data: {:confirm => t('are_you_sure')}, :method => :delete %>
<%# Upgrade 2.0.0 fine %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

<%# Upgrade 2.0.0 inizio %>
  <%#= will_paginate @creators %>
  <div class="digg_pagination">
    <%= will_paginate @creators, :container => false %>
  </div>
<%# Upgrade 2.0.0 fine %>

<% else %>
  <p>Non sono presenti schede soggetto produttore.</p>
<% end %>
</div>

<%# Upgrade 2.2.0 inizio %>
<% if current_user.is_multi_group_user?() %>
<%= render :partial => "creators/new_creator" %>
<% end %>
<%# Upgrade 2.2.0 fine %>

app/views/creators/new.html.erb
<% content_for :status_bar do %>
  <h2><%= status_bar_context %></h2>
  <div id="links">
    <%= link_to_index t('index_creators'), creators_path %>
  </div>
<% end %>

<%= render :partial => "form" %>

app/views/creators/show.html.erb
<% content_for :status_bar do %>
  <h2><%= status_bar_context %></h2>
  <div id="links">
    <%= link_to_index t('index_creators'), creators_path %>
  </div>
<% end %>

<div id="record-main" class="span9">
  <h3 class="section"><%= t('identification_area') %></h3>
  <table class="table-show">
    <tr>
      <th><%= t('creator_type') %></th>
      <td><%= show_value(@creator.creator_type, "t") %></td>
    </tr>

    <% if @creator.is_corporate? %>
      <tr>
        <th><%= t('creator_corporate_type') %></th>
        <td>
          <% if @creator.creator_corporate_type.present? %>
            <%= @creator.creator_corporate_type.corporate_type.capitalize %>
          <% else %>
            <%= blank_field %>
          <% end %>
        </td>
      </tr>
    <% end -%>

    <tr>
      <th><%= t('preferred_name') %></th>
      <td><%= @creator.preferred_name.name %> <%= show_item(@creator.preferred_name.note, ["[","]"]) %></td>
    </tr>

    <tr>
      <th><%= t('other_names')%></th>
      <td>
        <% if @creator.other_names.present? %>
          <ul>
            <% @creator.other_names.each do |other_name| %>
              <li>
                <%= show_item(other_name.name) %>
                <%= show_item(other_name.qualifier, ["<span>(",")</span>"], 't') %>
                <%= show_item(other_name.note, ["[","]"]) %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <%= blank_field %>
        <% end %>
      </td>
    </tr>

    <tr>
      <th><%= t('date_event')%></th>
      <td>
        <% if @creator.events.present? %>
          <% @creator.events.each do |ci| %>
            <%= ci.full_display_date_with_place %> <%= ci.note %>
          <% end %>
        <% else %>
          <%= blank_field %>
        <% end %>
      </td>
    </tr>


    <% if @creator.is_corporate? %>
      <tr>
        <th><%= t('creator_legal_status')%></th>
        <td>
          <% if @creator.creator_legal_statuses.present? %>
            <ul>
              <% @creator.creator_legal_statuses.each do |cls| %>
                <li><%= show_item(cls.legal_status, ['', ''], "t") %> <%= show_item(cls.note, ["[","]"]) %></li>
              <% end %>
            </ul>
          <% else %>
            <%= blank_field %>
          <% end %>
        </td>
      </tr>
    <% end %>

    <% if @creator.is_corporate? %>
      <tr>
        <th><%= t('residence') %></th>
        <td><%= show_value(@creator.residence) %></td>
      </tr>
    <% end %>
    <tr>
      <th><%= t('creator_urls')%></th>
      <td>
        <% if @creator.creator_urls.present? %>
          <ul>
            <% @creator.creator_urls.each do |cu_name| %>
              <li><%= link_to_unless(APP_EDITION == "standalone", cu_name.url, cu_name.url, { target: "_blank" } ) %> <%= show_item(cu_name.note, ["[","]"]) %></li>
            <% end -%>
          </ul>
        <% else %>
          <%= blank_field %>
        <% end %>
      </td>
    </tr>

    <tr>
      <th><%= t('creator_identifiers')%></th>
      <td>
        <% if @creator.creator_identifiers.present? %>
          <ul>
            <% @creator.creator_identifiers.each do |ci_name| %>
              <li>
                <%= show_item(ci_name.identifier) %>
                <%= show_item(ci_name.identifier_source, ["<span>(",")</span>"]) %>
                <%= show_item(ci_name.note, ["[","]"]) %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <%= blank_field %>
        <% end %>
      </td>
    </tr>
  </table>

  <h3 class="section"><%= t('description_area') %></h3>
  <table class="table-show">
    <tr>
      <th><%= t('abstract') %></th>
      <td><%= show_value(textilize(@creator.abstract)) %></td>
    </tr>

    <tr>
      <th><%= t('creator_history') %></th>
      <td><%= show_value(textilize(@creator.history)) %></td>
    </tr>

    <tr>
      <th><%= t('creator_note')%></th>
      <td><%= textilize(@creator.note) %></td>
    </tr>

    <tr>
      <th><%= t('activities')%></th>
      <td>
        <% if @creator.creator_activities.present? %>
          <ul>
            <% @creator.creator_activities.each do |creator_activity| %>
              <li>
                <%= show_item(creator_activity.activity) %>
                <%= show_item(creator_activity.note, ["[","]"]) %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <%= blank_field %>
        <% end %>
      </td>
    </tr>
  </table>

  <h3 class="section"><%= t('relationships_area') %></h3>
  <table class="table-show">
    <tr>
      <th><%= t('fonds')%></th>
      <%# FIXME: se fondo non root, dare path del fondo anziché solo nome %>
      <td>
        <% if @creator.fonds.present? %>
          <ul>
            <% @creator.fonds.each do |fond| %>
              <li><%= link_to "#{fond.name}", fond_path(fond) %>
                <%= fond.preferred_event.full_display_date if fond.preferred_event %></li>
            <% end -%>
          </ul>
        <% else %>
          <%= blank_field %>
        <% end %>
      </td>
    </tr>

    <% if @creator.is_corporate? %>
      <tr>
        <th><%= t('institutions')%></th>
        <td>
          <% if @creator.institutions.present? %>
            <ul>
              <% @creator.institutions.each do |institution| %>
                <li><%= link_to "#{institution.name}", institution_path(institution) %></li>
              <% end -%>
            </ul>
          <% else %>
            <%= blank_field %>
          <% end %>
        </td>
      </tr>
    <% end %>

    <tr>
      <th><%= t('linked_creators')%></th>
      <td>
        <% if @creator.rel_creator_creators.present? %>
          <ul>
            <% @creator.rel_creator_creators.each do |rel| %>
              <li>
    <%# FIXME: creator_association_type_id sarà sempre popolato %>
                (<%= rel.creator_association_type ? rel.creator_association_type.association_type : "legacy data: qualifica non presente" %>)
                <%= link_to rel.related_creator.preferred_name.name, creator_path(rel.related_creator) %>
                <%= rel.related_creator.preferred_event.full_display_date if rel.related_creator.preferred_event %>
              </li>
            <% end -%>
          </ul>
        <% else %>
          <%= blank_field %>
        <% end %>
      </td>
    </tr>
  </table>

<%# Upgrade 2.0.0 inizio %>
  <%#= render :partial => "shared/show_sources", :object => @creator.sources %>
  <%#= render :partial => "shared/show_editors", :object => @creator.creator_editors %>
  <%= render :partial => "shared/show_sources", :object => @creator.sources, as: "object" %>
  <%= render :partial => "shared/show_editors", :object => @creator.creator_editors, as: "object" %>
<%# Upgrade 2.0.0 fine %>

</div>

<%# Upgrade 2.0.0 inizio %>
<%#= render :partial => "shared/side", :object => @creator %>
<%= render :partial => "shared/side", :object => @creator, as: "object" %>
<%# Upgrade 2.0.0 fine %>