config/routes.rb
# Upgrade 2.0.0 inizio
Rails.application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resources :users do
    put 'toggle_active', on: :member
  end

  # Polymorphic resources (must be here, prior to parent resources)
  resources :digital_objects, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end
  resources :group_images, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end

  resources :groups do
    resources :group_carousel_images, :except => [:show, :destroy], :controller => "group_images", :type => "carousel"
    resources :group_logo_images, :except => [:show, :destroy], :controller => "group_images", :type => "logo"
  end

  resources :fonds, :except => [:new] do
    member do
      get    :tree
      get    :treeview
      put    :ajax_update
      patch  :ajax_update
      put    :rename
      put    :move
      get    :merge_with
      post   :merge
      get    :split_fond
      post   :split
      get    :trash
      get    :trashed_subtree
      put    :move_to_trash
      put    :restore_subtree
      delete :destroy_subtree
      put    :publish
      put    :unpublish
    end
    collection do
      get  :save_a_tree
      post :saving_the_tree
      get  :list
      post :ajax_create
    end

    resources :units do
      collection do
        get  :gridview
        post :gridview
        get  :grid
        post :add_rows
        put  :remove_rows
        put  :reorder_rows
# Upgrade 2.1.0 inizio
#        get  :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :units, :except => [:new] do
    member do
      put   :ajax_update
      patch :ajax_update
      get   :render_full_path
      get   :preferred_event
      get   :textfield_form
      put   :update_event
# Upgrade 2.1.0 inizio
#      get   :edit_iccd
#      get   :show_iccd
# Upgrade 2.1.0 fine
      get   :move
      post  :move_down
      post  :move_up
    end
    collection do
      get :list_oa_mtc
      get :list_oa_ogtd
      get :list_bdm_ogtd
      get :list_bdm_mtcm
      get :list_bdm_mtct
# Upgrade 2.1.0 inizio
      get :sc2_voc_list
# Upgrade 2.1.0 fine
      put :classify
    end

    # OPTIMIZE: rinominare in subunits ?
    resources :children, :controller => 'units', :only => 'new' do
      collection do
# Upgrade 2.1.0 inizio
#        get :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :creators do
    collection do 
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :custodians do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :sources do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :institutions do
    collection do
      get :list
    end
  end

  resources :document_forms do
    collection do
      get :list
    end
  end

  resources :projects do
    collection do
      get :list
      put :publish
      put :unpublish
    end
  end

  resources :editors do
    collection do
      get  :list
      get  :modal_new
      post :modal_create
    end
  end

  # Strumenti
  resources :headings do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :anagraphics do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :reports, :only => [:index] do
    member do
      get  :dashboard
      get  :summary
      get  :inventory
      post :inventory
      get  :creators
      get  :custodians
      get  :labels
      get  :units
      get  :custodian
      post :custodian
      get  :project
      post :project
    end
    collection do
      get :download
    end
  end

  resources :quality_checks, :only => [:index] do
    member do
      get :fond
      get :creator
      get :custodian
    end
  end

# Upgrade 3.0.0 inizio
resources :multiple_occours, :only => [:index] do
    member do
      post :merge
    end
  end
# Upgrade 3.0.0 fine

  resources :imports, :only => [:index, :new, :create, :destroy]
  resources :exports, :only => [:index] do
    collection do
      get :download
      get :xml
      get :fonds_aef
      get :units_ead
      # Upgrade 2.2.0 inizio
      post :units
      # Upgrade 2.2.0 fine
    end
  end
  resources :exports_batch, :only => [:index] do
    collection do
      post :icarimport
      post :aefallfonds
      post :aeffondsnoancestry
      post :aefallfondsnoancestry
      post :aefprojects
      post :aefallprojects
      post :aefcustodiansproject
      post :aefcustodians
      post :aefallcustodians
      post :xmlallfonds
      post :xmlfondsnoancestry
      post :xmlallfondsnoancestry
      post :xmlsourcesproject
      post :xmlsources
      post :xmlallsources
    end
  end    

  # Vocabolari
  resources :vocabularies, :only => [:index]

  resources :creator_corporate_types, :only => [:index]
  resources :custodian_types, :only => [:index]
  resources :source_types, :only => [:index]

  resources :activities, :only => [:index] do
    collection do
      get :list
    end
  end
  resources :places, :only => [:index] do
    collection do
      get :cities
      get :countries
    end
  end
  resources :langs, :only => [:index]

  # Non-Resourceful Routes
  root :to => 'site#dashboard'
  resources :about, :only => [:index], :to => "site#about"
  match :parse_textile, :only => [:index], :to => "site#parse_textile", :via => [:get, :post]

end

# Upgrade 2.0.0 fine

app/controllers/reports_controller.rb
# FIXME: custodian report => report vuoto se manca progetto

# TODO: valutare l'utilizzo di simple_format nelle viste

class ReportsController < ApplicationController

# Upgrade 2.0.0 inizio
  class PDFKitWrapper < PDFKit
    # Overwriting the command method.
    # la funzione command() contenuta nella versione 0.7.0 di pdfkit non produce delle command line corrette se ci sono caratteri come spazi, " (doppiapici), [] (parentesi quadre) in alcuni dei parametri. Questa è un adattamento della versione di command() presente nella versione 0.5.1
    def command(path = nil)
      # da pdfkit-0.5.1 - inizio
      # TAI 11/01/2016 per gestire correttamente i percorsi con eventuali spazi
      # args = [executable]
      strExe = executable
      if strExe.include? " "
        strExe = "\"" + strExe + "\""
      end
      args = [strExe]
      #
      args += @options.to_a.flatten.compact
      args << '--quiet'

      if @source.html?
        args << '-' # Get HTML from stdin
      else
        args << @source.to_s
      end
      # TAI 11/01/2016 per gestire correttamente i percorsi con eventuali spazi
      # args << (path || '-') # Write to file or stdout
      strPath = (path || '-') # Write to file or stdout
      if strPath.include? " "
        strPath = "\"" + strPath + "\""
      end
      args << strPath
      #
      args.map {|arg| %Q{"#{arg.gsub('"', '\"')}"}}
      # da pdfkit-0.5.1 - fine

      args.join(' ')  # da array a stringa
    end
  end
# Upgrade 2.0.0 fine

  LIMIT_FOR_PREVIEW = 100

  def index
    @fonds = Fond.list.
      roots.
      accessible_by(current_ability, :read).
      active.
      default_order

    # TODO: al momento l'interfaccia gestisce massimo 100 record. Fare
    # live_search (anziché paginate) ?
    @custodians = Custodian.export_list.accessible_by(current_ability, :read)
    @projects = Project.export_list.accessible_by(current_ability, :read)

    if params[:q].present? && params[:f].present?
      @fond = Fond.find(params[:f])
      if @fond
        redirect_to :action => 'dashboard', :id => @fond
      end
    end
    if params[:q].present? && params[:c].present?
      @custodian = Custodian.find(params[:c])
      if @custodian
        redirect_to :action => 'custodian', :id => @custodian
      end
    end
    if params[:q].present? && params[:p].present?
      @project = Project.find(params[:p])
      if @project
        redirect_to :action => 'project', :id => @project
      end
    end

  end

  def dashboard
# Upgrade 2.0.0 inizio
#    @fond = Fond.find(params[:id], :include => [:preferred_event, :creators, :custodians])
    @fond = Fond.includes([:preferred_event, :creators, :custodians]).find(params[:id])
# Upgrade 2.0.0 fine
    @units_count = @fond.active_descendant_units_count
  end

  def summary
# Upgrade 2.0.0 inizio
#    @fonds = Fond.subtree_of(params[:id]).active.all(:include => [:preferred_event], :order => "sequence_number")
#    @root_fond_name = @fonds.first.name
# @fond risulta non assegnato, da cui il fatto che è stata aggiunta l'istruzione che lo inizializza. Non è chiaro come poteva funzionare nella precedente versione
    #@fonds = Fond.subtree_of(params[:id]).active.includes([:preferred_event]).order("sequence_number")
    base_ids = [params[:id].to_i]
    tree_ordered_ids = tree_array(base_ids)


    @fonds = Fond.subtree_of(params[:id]).active.includes([:preferred_event]).sort_by{|thing| tree_ordered_ids.index thing.id}
    @fond = Fond.find(params[:id])
    @root_fond_name = @fond.name
    
# Upgrade 2.0.0 fine
    respond_to do |format|
      format.html
      format.pdf do
        filename = pdf_init("summary.html")
        render :json => {:file => "#{filename}.pdf"}
      end
    end
  end

  def tree_array(ids)
     arr = []
     ids.each do |node, children|
      children = Fond.children_of(node).active.order("position").map(&:id)
      arr << node
      arr += tree_array(children) unless children.empty? || children.nil?
     end
     arr
  end

  def inventory
    extend ReportSupport

    # ----------------
    @report_settings = ReportSettings.new(nil, "inventory", "Inventario di complesso archivistico", "inventory", nil)

    ers = EntityReportSettings.new(:project, project_available_attributes_info, false)
    @report_settings.entity_add(ers)

    ers = EntityReportSettings.new(:custodian, custodian_available_attributes_info, false)
    @report_settings.entity_add(ers)

    ers = EntityReportSettings.new(:creator, creator_available_attributes_info, false)
    @report_settings.entity_add(ers)

    ers = EntityReportSettings.new(:fond, fond_available_attributes_info, false)
    @report_settings.entity_add(ers)

    ers = EntityReportSettings.new(:unit, unit_available_attributes_info, false)
    @report_settings.entity_add(ers)

    # ----------------
    @report_settings.initialize_entities_selected_attribute_names(params, cookies)

    #@fonds = Fond.subtree_of(params[:id]).active.
    #  includes([
    #    :other_names, :fond_langs, :fond_owners, :fond_urls, :fond_identifiers, :fond_editors, :preferred_event, :sources,
    #    [:projects => [:project_managers, :project_stakeholders, :project_urls]],
    #    [:units => [:preferred_event, :unit_damages, :unit_other_reference_numbers, :unit_langs, :unit_urls, :unit_identifiers, :sources, :unit_editors, :iccd_description, :iccd_tech_spec, :iccd_authors, :iccd_subjects, :iccd_damages]],
    #    [:creators => [:preferred_name, :preferred_event, :other_names, :creator_legal_statuses, :creator_urls, :creator_identifiers, :creator_activities, :sources, :creator_editors]],
    #    [:custodians =>  [:preferred_name, :other_names, :custodian_contacts, :custodian_urls, :custodian_identifiers, :custodian_headquarter, :custodian_other_buildings, :sources, :custodian_editors]]
    #  ]).
    #  order("sequence_number")

    base_ids = [params[:id].to_i]
    tree_ordered_ids = tree_array(base_ids)

    @fonds = Fond.subtree_of(params[:id]).active.includes([
        :other_names, :fond_langs, :fond_owners, :fond_urls, :fond_identifiers, :fond_editors, :preferred_event, :sources,
        [:projects => [:project_managers, :project_stakeholders, :project_urls]],
        [:units => [:preferred_event, :unit_damages, :unit_other_reference_numbers, :unit_langs, :unit_urls, :unit_identifiers, :sources, :unit_editors, :iccd_description, :iccd_tech_spec, :iccd_authors, :iccd_subjects, :iccd_damages]],
        [:creators => [:preferred_name, :preferred_event, :other_names, :creator_legal_statuses, :creator_urls, :creator_identifiers, :creator_activities, :sources, :creator_editors]],
        [:custodians =>  [:preferred_name, :other_names, :custodian_contacts, :custodian_urls, :custodian_identifiers, :custodian_headquarter, :custodian_other_buildings, :sources, :custodian_editors]]
      ]).sort_by{|thing| tree_ordered_ids.index thing.id}

    @root_fond = @fonds.first
    @display_sequence_numbers = Unit.display_sequence_numbers_of(@root_fond)

    respond_to do |format|
      format.html
      format.pdf do
        filename = pdf_init("inventory.html")
        render :json => {:file => "#{filename}.pdf"}
      end
      format.rtf do
        filename = "inventory-#{Time.now.strftime('%Y%m%d%H%M%S')}"
        @builder = RtfBuilder.new
        @builder.target_id = params[:id]
        @builder.dest_file = "#{Rails.root}/public/downloads/#{filename}.rtf"
        @builder.build_fond_rtf_file(params, cookies)
        render :json => {:file => "#{filename}.rtf"}
        return
      end
    end
  end

  def creators
# Upgrade 2.0.0 inizio
#    fonds =  Fond.subtree_of(params[:id]).active.all(:include => [:creators => [:preferred_name, :preferred_event]], :order => "sequence_number")
#    @root_fond_name = fonds.first.name
# @fond risulta non assegnato, da cui il fatto che è stata aggiunta l'istruzione che lo inizializza. Non è chiaro come poteva funzionare nella precedente versione
    fonds =  Fond.subtree_of(params[:id]).active.includes([:creators => [:preferred_name, :preferred_event]]).order("sequence_number")
    @fond = fonds.find(params[:id])
    @root_fond_name = @fond.name
# Upgrade 2.0.0 fine

    ids = fonds.map(&:id).join(',')

# Upgrade 2.0.0 inizio
=begin
    @creators  =  Creator.all(
      :joins => :rel_creator_fonds,
      :conditions => "rel_creator_fonds.fond_id IN (#{ids})",
      :include => [:preferred_name, :preferred_event]).uniq
=end
    @creators  =  Creator.
      joins(:rel_creator_fonds).
      where("rel_creator_fonds.fond_id IN (#{ids})").
      includes([:preferred_name, :preferred_event]).uniq
# Upgrade 2.0.0 fine
    respond_to do |format|
      format.html
      format.pdf do
        filename = pdf_init("creators.html")
        render :json => {:file => "#{filename}.pdf"}
      end
    end
  end

  def units
    units_list("units.html")
  end

  def labels
    units_list("labels.html")
  end

  def project
    extend ReportSupport

    # ----------------
    @report_settings = ReportSettings.new(nil, "project", "report per progetto", "project", nil)

    ers = EntityReportSettings.new(:project, project_available_attributes_info, false)
    @report_settings.entity_add(ers)

    ers = EntityReportSettings.new(:custodian, custodian_available_attributes_info, false)
    @report_settings.entity_add(ers)

    ers = EntityReportSettings.new(:creator, creator_available_attributes_info, false)
    @report_settings.entity_add(ers)

    ers = EntityReportSettings.new(:fond, fond_available_attributes_info, false)
    @report_settings.entity_add(ers)

    ers = EntityReportSettings.new(:unit, unit_available_attributes_info, false)
    @report_settings.entity_add(ers)

    # ----------------
    @report_settings.initialize_entities_selected_attribute_names(params, cookies)

=begin
    @project_fields = [
      "project_type",
      "display_date",
      "description"
    ]

    @fond_fields = [
      "preferred_event.full_display_date",
      "extent",
      "description",

app/views/reports/_form_custodians.html.erb
<p>Seleziona un soggetto conservatore</p>
<%# TAI aggiunto = prima di form_tag %>
<%= form_tag("/reports", :method => :get, :id => "reports-custodian-choice", :class => "skip-prompt export-wait") do %>
  <div style="margin: 7px 0 0 0;">
    <div>
      <span class="ui-icon ui-icon-search" style="display:inline; float:left; margin: 5px 0 0 0;">&nbsp;</span>
    </div>
    <div style="margin-left:16px; padding-left:10px;">
      <%= text_field_tag :q, params[:q], :id => "reports-custodian-name-autocomplete",
        :class => "autocomplete",
        :'data-autocompletion-controller' => 'custodians',
        :'data-autocompletion-action' => 'list',
        :style => "width:600px;" %>
      <%= hidden_field_tag :c, "", :id => "reports-custodian-id-autocomplete" %>
    </div>
  </div>
<% end %>

app/views/reports/_form_fonds.html.erb
<%# TAI aggiunto = prima di form_tag %>
<%= form_tag("/reports", :method => :get, :id => "reports-fond-choice", :class => "skip-prompt") do %>
  <i class="icon-search"></i>
  <%= text_field_tag :q, params[:q], :id => "reports-fond-name-autocomplete",
    :class => "autocomplete span6",
    :placeholder => "Cerca un complesso archivistico",
    :'data-autocompletion-controller' => 'fonds' %>
  <%= hidden_field_tag :f, "", :id => "reports-fond-id-autocomplete" %>
<% end %>

app/views/reports/_preview_disclaimer.html.erb
<div id="preview-disclaimer">
  <% if count > ReportsController::LIMIT_FOR_PREVIEW %>
    <p>
      Anteprima di <%= ReportsController::LIMIT_FOR_PREVIEW %> elementi su un totale di <strong><%= number_with_delimiter(count) %></strong> selezionati.
      <span class="muted">I file generati forniscono sempre un report completo degli elementi selezionati.</span>
    </p>
  <% else %>
    <p>Elementi selezionati: <strong><%= number_with_delimiter(count) %></strong></p>
  <% end %>
</div>

app/views/reports/dashboard.html.erb
<% content_for :status_bar do %>
  <h2>Report complesso archivistico<%= path_separator %><%= @fond.name %></h2>
  <div id="links">
    <%= link_to_index "Report", reports_path %>
  </div>
<% end %>


<div class="span8">
  <h2>
    <%= @fond.name %>
    <span class="date"><%= @fond.preferred_event.try(:full_display_date) %></span>
  </h2>

  <!-- <h3>Placeholder</h3> -->

  <table class="table" style="margin-top: 1em">
    <tbody>
      <tr>
        <td><%= link_to 'Inventario', inventory_report_path(@fond) %></td>
      </tr>
      <tr>
        <td><%= link_to_if @units_count > 0, 'Etichette unità', labels_report_path(@fond, :mode => "preview") %>
            (<%= number_with_delimiter(@units_count) || "0" %>)
          </td>
      </tr>
    </tbody>
  </table>

  <!-- <h3>Placeholder</h3> -->

  <table class="table">
    <tbody>
      <tr>
        <td><%= link_to 'Struttura complesso archivistico', summary_report_path(@fond) %></td>
      </tr>
      <tr>
        <td><%= link_to_if @units_count > 0, "Lista unità", units_report_path(@fond, :mode => "preview") %>
           (<%= number_with_delimiter(@units_count) || "0" %>)</td>
      </tr>
      <tr>
        <td><%= link_to_if @fond.creators.present?, "Lista soggetti produttori", creators_report_path(@fond) %>
          (<%= @fond.creators.size || "0" %>)</td>
      </tr>
    </tbody>
  </table>

</div>

app/views/reports/inventory.html.erb
<% content_for :status_bar do %>
  <h2>Report complesso archivistico<%= path_separator %><%= link_to @root_fond.name, dashboard_report_path %><%= path_separator %>Inventario</h2>
  <div id="links">
    <%= link_to_index "Report", reports_path %>
  </div>
<% end %>
<div class="span9">
  <div id="index-controls">
    <%= link_to raw('<i class="icon-download-alt"></i> Genera RTF'), inventory_report_path(@root_fond, :format => "rtf"), {:class => "rtf btn btn-small"} %>
    <%= link_to raw('<i class="icon-download-alt"></i> Genera PDF'), inventory_report_path(@root_fond, :format => "pdf"), {:class => "pdf btn btn-small"} %>
    <button id="select-report-columns" data-target="#report-settings-dialog" data-toggle="modal" class="btn btn-small" tabindex="-1">
      <i class="icon-cog"></i>&nbsp;Impostazioni report
    </button>
    <%= render :partial => 'reports/report_settings' %>
  </div>

	<div class="report_content">
    <% extend ReportSupport %>

    <% fond_index = 0 %>
    <% fond_count = @fonds.size %>

    <% @fonds.each do |fond| %>
      <div class="pbi_avoid">
        <h2>
          <%= fond.name %>
          <% if fond.preferred_event.present? %>
            <span class="date"><%= fond.preferred_event.full_display_date %></span>
          <% end %>
        </h2>

        <% if fond.projects.present? %>
          <h3><%= Project.model_name.human({:count => fond.projects.size}) %></h3>
          <% fond.projects.each do |project| %>
            <h4><%= project.display_name %></h4>
            <%= raw(make_html(@report_settings, :project, project)) %>
          <% end %>
          <% insert_separator = true %>
        <% end %>

        <% if fond.custodians.present? %>
          <% if insert_separator %>
            <hr />
          <% end %>
          <h3><%= Custodian.model_name.human({:count => fond.custodians.size}) %></h3>
          <% fond.custodians.each do |custodian| %>
            <h4><%= custodian.display_name %></h4>
            <%= raw(make_html(@report_settings, :custodian, custodian)) %>
          <% end %>
          <% insert_separator = true %>
        <% end %>

        <% if fond.creators.present? %>
          <% if insert_separator %>
            <hr />
          <% end %>
          <% insert_separator = true %>
          <h3><%= Creator.model_name.human({:count => fond.creators.size}) %></h3>
          <% creators = fond.creators.sort{|a,b| a.display_name <=> b.display_name} %>
          <% creators.each do |creator| %>
            <h4><%= creator.display_name %></h4>
            <%= raw(make_html(@report_settings, :creator, creator)) %>
          <% end %>
        <% end %>

        <% if insert_separator %>
          <hr />
        <% end %>
        <%= raw(make_html(@report_settings, :fond, fond)) %>

        <% if fond.units.present? %>
          <% if insert_separator %>
            <hr />
          <% end %>
          <% insert_separator = true %>

          <h3><%= Unit.model_name.human({:count => fond.units.size}) %></h3>
          <% fond.units.each do |u| %>
            <div class="pbi_avoid">
              <p class="head">
                <span class="pull-left"><strong><%= u.display_sequence_number_from_hash(@display_sequence_numbers) %></strong></span>
              </p>
              <h4><%= u.formatted_title %></h4>
              <%= raw(make_html(@report_settings, :unit, u)) %>
            </div>
          <% end %>
        <% end %>
        
      </div>
      <% if fond_index < fond_count - 1 then %> <hr /> <% end %>
      <% fond_index += 1 %>      
    <% end %>
  </div>

</div>

app/views/reports/labels.html.erb
<% content_for :status_bar do %>
  <h2>
<%# TAI aggiunto raw() %>
    <%= raw([
      'Report complesso archivistico',
      link_to(@fond.root.name, dashboard_report_path(@fond.root.id)),
      'Etichette unità'
    ].join(path_separator)) %>
  </h2>
  <div id="links">
    <%= link_to_index "Report", reports_path %>
  </div>
<% end %>

<div class="span12">
  <div id="index-controls">
<%# Upgrade 2.0.0 inizio %>
    <%#= link_to '<i class="icon-download-alt"></i> Genera CSV', labels_report_path(@fond, params.merge({:format => "csv", :mode => nil})), {:class => "csv btn btn-small"} %>
    <%#= link_to '<i class="icon-download-alt"></i> Genera XLS', labels_report_path(@fond, params.merge({:format => "xls", :mode => nil})), {:class => "xls btn btn-small"} %>
    <%#= link_to '<i class="icon-download-alt"></i> Genera PDF', labels_report_path(@fond, params.merge({:format => "pdf", :mode => nil})), {:class => "pdf btn btn-small"} %>
    <%= link_to raw('<i class="icon-download-alt"></i> Genera CSV'), labels_report_path(@fond, params.merge({:format => "csv", :mode => nil})), {:class => "csv btn btn-small"} %>
    <%= link_to raw('<i class="icon-download-alt"></i> Genera XLS'), labels_report_path(@fond, params.merge({:format => "xls", :mode => nil})), {:class => "xls btn btn-small"} %>
    <%= link_to raw('<i class="icon-download-alt"></i> Genera PDF'), labels_report_path(@fond, params.merge({:format => "pdf", :mode => nil})), {:class => "pdf btn btn-small"} %>
<%# Upgrade 2.0.0 fine %>
  </div>

  <%= render :partial => 'subtree_selector.html', :locals => {:root_id => @fond.root.id, :fond_id => @fond.id} %>

  <%= render :partial => 'preview_disclaimer.html', :locals => {:count => @units_count} %>

  <% if @units.any? %>
    <table style="margin:auto;" id="labels">
      <% @units.each_slice(2) do |row| %>
        <tr>
          <% row.each do |unit| %>
            <td>
              <div class="unit-label pbi_avoid">
                <p>
                  <strong><%= @fond.root.name %></strong><br />
                  <%= unit.fond.name %><br />
                  <em><%= unit.title %></em><br />
                  <%= unit.preferred_event.try(:full_display_date_with_place) || "[s.d.]" %><br />
                  <%= unit.reference_number %>
                </p>
              </div>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p id="turn-off-buttons">Non sono presenti unità nei livelli selezionati.</p>
  <% end %>
</div>

app/views/reports/labels.xls.erb
<%= render :partial => 'xls_template', :locals => {:units => @units, :root_name => @fond.root.name, :sequence_numbers => @display_sequence_numbers} %>

app/views/reports/summary.html.erb
<% content_for :status_bar do %>
  <h2>Report complesso archivistico<%= path_separator %><%= link_to @root_fond_name, dashboard_report_path %><%= path_separator %>Struttura complesso archivistico</h2>
  <div id="links">
    <%= link_to_index "Report", reports_path %>
  </div>
<% end %>

<div class="span12">
  <div id="index-controls">
<%# Upgrade 2.0.0 inizio %>
    <%#= link_to '<i class="icon-download-alt"></i> Genera PDF', summary_report_path(@fond, :format => "pdf"),  {:class => "btn btn-small pdf"}  %>
    <%= link_to raw('<i class="icon-download-alt"></i> Genera PDF'), summary_report_path(@fond, :format => "pdf"),  {:class => "btn btn-small pdf"}  %>
<%# Upgrade 2.0.0 fine %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th><%= t('short_fond_type') %></th>
        <th><%= t('name') %></th>
        <th><%= t('date_event') %> </th>
        <th><%= t('short_units_count') %></th>
      </tr>
    </thead>
    <tbody>
      <% @fonds.each do |f| %>
        <tr>
          <td><div class="pbi_avoid"><%= f.fond_type %></div></td>
<%# TAI aggiunto raw() %>
          <td><div class="pbi_avoid"><%= raw("&mdash;" * f.ancestry_depth) %> <%= f.name %></div></td>
          <td class="fixed-large"><div class="pbi_avoid"><%= f.preferred_event.try(:full_display_date_with_place) %></div></td>
          <td><div class="pbi_avoid"><%= f.try(:units_count) %></div></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>